name: Obfuscate Python File

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggers

jobs:
  obfuscate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Specify the Python version you need

      # Step 3: Install PyArmor
      - name: Install PyArmor
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Obfuscate the Python file
      - name: Obfuscate Python File
        run: |
          mkdir -p obfuscated_files
          pyarmor gen -O obfuscated_files main.py

       # Step 5: Build an executable with PyInstaller
      - name: Build Executable
        run: |
          mkdir -p build_output
          pyinstaller --onefile --distpath build_output obfuscated_files/main.py

      # Optional: Upload obfuscated files as an artifact
      - name: Upload Obfuscated Files
        uses: actions/upload-artifact@v3
        with:
          name: obfuscated-files
          path: obfuscated_files
